### ISSUE TITLE
runtime error

### ISSUE THREAD

**Issue by pinpins** [xumacoin/xuma-core#7]
/usr/include/c++/4.8/debug/safe_iterator.h:506:error: attempt to compare a
    dereferenceable iterator to a singular iterator.

Objects involved in the operation:
iterator "lhs" @ 0x0x7ff2debd66e0 {
type = N11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIP11CMasternodeNSt9__cxx19986vectorIS3_Sa                  IS3_EEEEENSt7__debug6vectorIS3_S7_EEEE (mutable iterator);
  state = dereferenceable;
  references sequence with type `NSt7__debug6vectorI11CMasternodeSaIS1_EEE' @ 0x0x1140bb0
}
iterator "rhs" @ 0x0x7ff2debd6710 {
type = N11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIP11CMasternodeNSt9__cxx19986vectorIS3_Sa                  IS3_EEEEENSt7__debug6vectorIS3_S7_EEEE (mutable iterator);
  state = singular;
  references sequence with type `NSt7__debug6vectorI11CMasternodeSaIS1_EEE' @ 0x0x1140bb0
}

**Comment by somhi** [comment]
similar problems here

/usr/include/c++/4.8/debug/safe_iterator.h:264:
Error: attempt to dereference a past-the-end iterator.

Objects involved in the operation:
    iterator "this" @ 0x0x10ca960 {
      type = segment violation

**Comment by makumori** [comment]
Please compile from source. I've only seen this error occasionally from the binaries but never from source.
