### ISSUE TITLE
Object involved in the operation

### ISSUE THREAD

**Issue by Poolovich** [xumacoin/xuma-core#8]
Wallet new version 1.1.2 , after starting error will be.

 /usr/include/c++/4.8/debug/safe_iterator.h:506:error: attempt to compare a
    dereferenceable iterator to a singular iterator.

Objects involved in the operation:
iterator "lhs" @ 0x0x7f8d3ebdb6e0 {
type = N11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIP11CMasternodeNSt9__cxx19986vectorIS3_SaIS3_EEEEENSt7__debug6vectorIS3_S7_EEEE (mutable iterator);
  state = dereferenceable;
  references sequence with type `NSt7__debug6vectorI11CMasternodeSaIS1_EEE' @ 0x0x1140bb0
}
iterator "rhs" @ 0x0x7f8d3ebdb710 {
type = N11__gnu_debug14_Safe_iteratorIN9__gnu_cxx17__normal_iteratorIP11CMasternodeNSt9__cxx19986vectorIS3_SaIS3_EEEEENSt7__debug6vectorIS3_S7_EEEE (mutable iterator);
  state = singular;
  references sequence with type `NSt7__debug6vectorI11CMasternodeSaIS1_EEE' @ 0x0x1140bb0

**Comment by mhannigan** [comment]
Can you please provide some additional context that would make it straightforward to reproduce the error.  For example, step1. Expect to See/do see, Step 2. Expect to See/do see....
