### ISSUE TITLE
Make `xumad` work with a pre-existing `xuma.conf`

### ISSUE THREAD

**Issue by thasmo** [xumacoin/xuma-core#9]
Currently setting up `xumad` is a multi-step process where the first step is running `xumad` to create initial directories and files, the second step is adapting the created `xuma.conf` and the third step is to run `xumad` again.

Especially when running `xumad` within a `docker` container, where mounting the `.xuma` directory is recommended (to not lose data), this setup process is kinda cumbersome, because currently it's not possible to simply mount the `.xuma` directory and be done.

The main issue comes from the fact that it's needed to tun `xumad` initially to create all needed directories and files. When running `xumad` with an existing `xuma.conf`, it just creates the `masternode.conf` and the `debug.log` file and dies without any useful message.

What I propose is that `xumad` should be able to handle the initial run with an existing `xuma.conf` file and still create all needed directories and files.

This would make running `docker run -v ./data/:/home/xuma/.xuma/ my-xuma-image` (with an existing `xuma.conf` in `/data/`) so much easier and it would actually be `docker`-friendly in the first place.

**Comment by makumori** [comment]
Can you provide more details about the use case where you provide the xuma.conf before first run? On a Mac, I started with just a xuma.conf file and it didn't quit like you mentioned. Instead xumad starts downloading blocks and works as expected.
